"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { getItems, getIncomeSummary, getPayrollSummary } from "@/lib/api"
import type { Payment, Expense, Fee, PayrollRecord, Income, InstitutionSettings } from "@/lib/types"
import { Loader2, Download, FileText, FileSpreadsheet } from "lucide-react"

function exportToCSV(filename: string, headers: string[], rows: string[][]) {
  const csv = [headers.join(","), ...rows.map(r => r.map(c => `"${c}"`).join(","))].join("\n")
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" })
  const link = document.createElement("a")
  link.href = URL.createObjectURL(blob)
  link.download = `${filename}.csv`
  link.click()
  URL.revokeObjectURL(link.href)
}

function exportToPDF(title: string, headers: string[], rows: string[][], summary?: { label: string; value: string }[]) {
  const printWindow = window.open("", "_blank")
  if (!printWindow) { alert("Please allow pop-ups to export PDF"); return }
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
  const summaryHtml = summary
    ? `<div style="margin-top:24px;padding:16px;background:#f8f9fa;border-radius:6px;border:1px solid #e5e7eb">
         <table style="width:auto;border:none">
           ${summary.map(s => `<tr><td style="padding:4px 24px 4px 0;font-size:13px;font-weight:500;color:#6b7280;border:none">${s.label}</td><td style="padding:4px 0;font-size:13px;font-weight:700;color:#111827;border:none">${s.value}</td></tr>`).join("")}
         </table>
       </div>`
    : ""
  printWindow.document.write(`
    <html><head><title>${title}</title>
    <style>
      @page { margin: 0.75in 0.5in; }
      body { font-family: "Segoe UI", Arial, sans-serif; padding: 0; margin: 0; color: #111; font-size: 12px; }
      .header { border-bottom: 3px solid #1a1a2e; padding-bottom: 16px; margin-bottom: 20px; }
      .header h1 { font-size: 16px; margin: 0 0 2px; letter-spacing: 0.03em; text-transform: uppercase; color: #1a1a2e; }
      .header .sub { font-size: 11px; color: #6b7280; margin: 0; }
      .header .report-title { font-size: 20px; font-weight: 700; margin: 8px 0 0; color: #1a1a2e; }
      .header .report-date { font-size: 11px; color: #9ca3af; margin: 2px 0 0; }
      table { width: 100%; border-collapse: collapse; margin-top: 8px; }
      th { background: #1a1a2e; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; }
      td { padding: 7px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
      tr:nth-child(even) td { background: #f9fafb; }
      .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    </style></head><body>
    <div class="header">
      <h1>Trainify Technology Training Institute</h1>
      <p class="sub">Official Financial Report</p>
      <div class="report-title">${title}</div>
      <div class="report-date">Generated: ${today}</div>
    </div>
    <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr></thead>
    <tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>
    ${summaryHtml}
    <div class="footer">Generated by Trainify Technology Training Institute &mdash; ${today}</div>
    </body></html>
  `)
  printWindow.document.close()
  printWindow.print()
}

export default function ReportsPage() {
  const [payments, setPayments] = useState<Payment[]>([])
  const [expenses, setExpenses] = useState<Expense[]>([])
  const [fees, setFees] = useState<Fee[]>([])
  const [payrollRecords, setPayrollRecords] = useState<PayrollRecord[]>([])
  const [incomeList, setIncomeList] = useState<Income[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [dateRange, setDateRange] = useState({
    from: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split("T")[0],
    to: new Date().toISOString().split("T")[0],
  })
  const [currency, setCurrency] = useState("KES")

  useEffect(() => { loadData() }, [])

  const loadData = async () => {
    setIsLoading(true)
    try {
      const [p, e, f, settings, payroll, income] = await Promise.all([
        getItems<Payment>("payments"),
        getItems<Expense>("expenses"),
        getItems<Fee>("fees"),
        getItems<InstitutionSettings>("institutionSettings"),
        getItems<PayrollRecord>("payrollRecords"),
        getItems<Income>("income"),
      ])
      setPayments(p)
      setExpenses(e)
      setFees(f)
      setPayrollRecords(payroll)
      setIncomeList(income)
      if (settings.length > 0) setCurrency(settings[0].currency || "KES")
    } catch (error) {
      console.error("Failed to load data", error)
    } finally {
      setIsLoading(false)
    }
  }

  const filterByDateRange = <T extends { paymentDate?: string; expenseDate?: string; createdAt?: string }>(
    items: T[], dateField: "paymentDate" | "expenseDate" | "createdAt"
  ) => {
    return items.filter(item => {
      const d = item[dateField]
      if (!d) return true
      return d >= dateRange.from && d <= dateRange.to
    })
  }

  const filteredPayments = filterByDateRange(payments, "paymentDate")
  const filteredExpenses = filterByDateRange(expenses, "expenseDate")

  const totalIncome = filteredPayments.reduce((s, p) => s + Number(p.amount), 0)
  const totalExpensesAmt = filteredExpenses.reduce((s, e) => s + Number(e.amount), 0)
  const outstandingTotal = fees.filter(f => f.status !== "PAID").reduce((s, f) => s + Number(f.balance || 0), 0)
  const totalPayroll = payrollRecords.filter(r => r.status === "PAID").reduce((s, r) => s + Number(r.amount), 0)
  const totalOtherIncome = incomeList.reduce((s, i) => s + Number(i.amount), 0)
  const totalAllIncome = totalIncome + totalOtherIncome

  // Daily income aggregation
  const dailyIncome: Record<string, number> = {}
  filteredPayments.forEach(p => {
    dailyIncome[p.paymentDate] = (dailyIncome[p.paymentDate] || 0) + Number(p.amount)
  })

  // Expense by category
  const expensesByCategory: Record<string, number> = {}
  filteredExpenses.forEach(e => {
    expensesByCategory[e.category] = (expensesByCategory[e.category] || 0) + Number(e.amount)
  })

  const handleExportIncomePDF = () => {
    const headers = ["Date", "Student", "Amount", "Method", "Receipt"]
    const rows = filteredPayments.map(p => [p.paymentDate, `${p.firstName || ""} ${p.lastName || ""}`, `${currency} ${Number(p.amount).toLocaleString()}`, p.paymentMethod.replace("_", " "), p.receiptNumber])
    exportToPDF("Income Report", headers, rows, [{ label: "Total Income", value: `${currency} ${totalIncome.toLocaleString()}` }, { label: "Transactions", value: filteredPayments.length.toString() }])
  }

  const handleExportIncomeCSV = () => {
    exportToCSV("income_report", ["Date", "Student", "Amount", "Method", "Receipt"],
      filteredPayments.map(p => [p.paymentDate, `${p.firstName || ""} ${p.lastName || ""}`, Number(p.amount).toString(), p.paymentMethod, p.receiptNumber]))
  }

  const handleExportExpensesPDF = () => {
    const headers = ["Date", "Category", "Description", "Amount", "Receipt"]
    const rows = filteredExpenses.map(e => [e.expenseDate, e.category.replace("_", " "), e.description, `${currency} ${Number(e.amount).toLocaleString()}`, e.receiptNumber || ""])
    exportToPDF("Expense Report", headers, rows, [{ label: "Total Expenses", value: `${currency} ${totalExpensesAmt.toLocaleString()}` }, { label: "Transactions", value: filteredExpenses.length.toString() }])
  }

  const handleExportExpensesCSV = () => {
    exportToCSV("expense_report", ["Date", "Category", "Description", "Amount", "Receipt"],
      filteredExpenses.map(e => [e.expenseDate, e.category, e.description, Number(e.amount).toString(), e.receiptNumber || ""]))
  }

  const handleExportOutstandingPDF = () => {
    const outstandingFees = fees.filter(f => f.status !== "PAID")
    const headers = ["Student", "Course", "Total Fee", "Balance", "Status"]
    const rows = outstandingFees.map(f => [`${f.firstName || ""} ${f.lastName || ""}`, f.courseName || "", `${currency} ${Number(f.totalFee).toLocaleString()}`, `${currency} ${Number(f.balance).toLocaleString()}`, f.status])
    exportToPDF("Outstanding Balance Report", headers, rows, [{ label: "Total Outstanding", value: `${currency} ${outstandingTotal.toLocaleString()}` }, { label: "Students", value: outstandingFees.length.toString() }])
  }

  const handleExportOutstandingCSV = () => {
    const outstandingFees = fees.filter(f => f.status !== "PAID")
    exportToCSV("outstanding_balances", ["Student", "Course", "Total Fee", "Balance", "Status"],
      outstandingFees.map(f => [`${f.firstName || ""} ${f.lastName || ""}`, f.courseName || "", Number(f.totalFee).toString(), Number(f.balance).toString(), f.status]))
  }

  const handleExportCashFlowPDF = () => {
    const headers = ["Metric", "Amount"]
    const rows = [
      ["Total Income", `${currency} ${totalIncome.toLocaleString()}`],
      ["Total Expenses", `${currency} ${totalExpensesAmt.toLocaleString()}`],
      ["Net Cash Flow", `${currency} ${(totalIncome - totalExpensesAmt).toLocaleString()}`],
      ["Outstanding Balances", `${currency} ${outstandingTotal.toLocaleString()}`],
    ]
    exportToPDF("Cash Flow Summary", headers, rows)
  }

  const handleExportProfitLossPDF = () => {
    const headers = ["Metric", "Amount"]
    const rows = [
      ["Total Income (Fees)", `${currency} ${totalIncome.toLocaleString()}`],
      ["Total Expenses", `${currency} ${totalExpensesAmt.toLocaleString()}`],
      ["---"],
      ["Profit / Loss", `${currency} ${(totalIncome - totalExpensesAmt).toLocaleString()}`],
    ]
    exportToPDF("Profit & Loss Summary", headers, rows)
  }

  if (isLoading) {
    return (
      <div className="flex justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>
    )
  }

  return (
    <>
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Date Range</CardTitle>
            <CardDescription>Filter reports by date</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex gap-4 items-end">
              <div>
                <Label>From</Label>
                <Input type="date" value={dateRange.from} onChange={(e) => setDateRange({ ...dateRange, from: e.target.value })} />
              </div>
              <div>
                <Label>To</Label>
                <Input type="date" value={dateRange.to} onChange={(e) => setDateRange({ ...dateRange, to: e.target.value })} />
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="grid gap-4 md:grid-cols-4 mb-6">
          <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Total Revenue</CardTitle></CardHeader>
            <CardContent><div className="text-2xl font-bold text-green-600">{currency} {totalAllIncome.toLocaleString()}</div></CardContent></Card>
          <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Expenses</CardTitle></CardHeader>
            <CardContent><div className="text-2xl font-bold text-red-600">{currency} {totalExpensesAmt.toLocaleString()}</div></CardContent></Card>
          <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Net Cash Flow</CardTitle></CardHeader>
            <CardContent><div className={`text-2xl font-bold ${totalAllIncome - totalExpensesAmt >= 0 ? "text-green-600" : "text-red-600"}`}>{currency} {(totalAllIncome - totalExpensesAmt).toLocaleString()}</div></CardContent></Card>
          <Card><CardHeader className="pb-2"><CardTitle className="text-sm">Outstanding</CardTitle></CardHeader>
            <CardContent><div className="text-2xl font-bold text-orange-600">{currency} {outstandingTotal.toLocaleString()}</div></CardContent></Card>
        </div>

        <Tabs defaultValue="income">
          <TabsList className="mb-4 flex-wrap">
            <TabsTrigger value="income">Fee Income</TabsTrigger>
            <TabsTrigger value="otherIncome">Other Income</TabsTrigger>
            <TabsTrigger value="expenses">Expenses</TabsTrigger>
            <TabsTrigger value="payroll">Payroll</TabsTrigger>
            <TabsTrigger value="outstanding">Outstanding</TabsTrigger>
            <TabsTrigger value="cashflow">Cash Flow</TabsTrigger>
          </TabsList>

          <TabsContent value="income">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Income Report</CardTitle>
                    <CardDescription>Payments received in the selected period</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportIncomePDF}><FileText className="h-4 w-4 mr-1" /> PDF</Button>
                    <Button variant="outline" size="sm" onClick={handleExportIncomeCSV}><FileSpreadsheet className="h-4 w-4 mr-1" /> CSV</Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Date</TableHead><TableHead>Student</TableHead><TableHead>Amount</TableHead><TableHead>Method</TableHead><TableHead>Receipt</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredPayments.length === 0 ? (
                      <TableRow><TableCell colSpan={5} className="text-center h-24 text-muted-foreground">No payments in this period</TableCell></TableRow>
                    ) : (
                      filteredPayments.map(p => (
                        <TableRow key={p.id}>
                          <TableCell>{p.paymentDate}</TableCell>
                          <TableCell>{p.firstName} {p.lastName}</TableCell>
                          <TableCell>{currency} {Number(p.amount).toLocaleString()}</TableCell>
                          <TableCell>{p.paymentMethod.replace("_", " ")}</TableCell>
                          <TableCell className="font-mono text-xs">{p.receiptNumber}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
                <div className="mt-4 text-right font-bold">Total: {currency} {totalIncome.toLocaleString()}</div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="expenses">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Expense Report</CardTitle>
                    <CardDescription>Expenses in the selected period</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportExpensesPDF}><FileText className="h-4 w-4 mr-1" /> PDF</Button>
                    <Button variant="outline" size="sm" onClick={handleExportExpensesCSV}><FileSpreadsheet className="h-4 w-4 mr-1" /> CSV</Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-4 mb-4">
                  {Object.entries(expensesByCategory).map(([cat, amt]) => (
                    <Card key={cat}>
                      <CardHeader className="pb-2"><CardTitle className="text-xs">{cat.replace("_", " ")}</CardTitle></CardHeader>
                      <CardContent><div className="font-bold">{currency} {amt.toLocaleString()}</div></CardContent>
                    </Card>
                  ))}
                </div>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Amount</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredExpenses.length === 0 ? (
                      <TableRow><TableCell colSpan={4} className="text-center h-24 text-muted-foreground">No expenses in this period</TableCell></TableRow>
                    ) : (
                      filteredExpenses.map(e => (
                        <TableRow key={e.id}>
                          <TableCell>{e.expenseDate}</TableCell>
                          <TableCell>{e.category.replace("_", " ")}</TableCell>
                          <TableCell>{e.description}</TableCell>
                          <TableCell>{currency} {Number(e.amount).toLocaleString()}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
                <div className="mt-4 text-right font-bold">Total: {currency} {totalExpensesAmt.toLocaleString()}</div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="otherIncome">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Other Income Report</CardTitle>
                    <CardDescription>Non-fee income sources</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-4 mb-4">
                  {["FEES", "GRANTS", "DONATIONS", "OTHER"].map((cat) => {
                    const total = incomeList.filter(i => i.category === cat).reduce((s, i) => s + Number(i.amount), 0)
                    return total > 0 ? (
                      <Card key={cat}><CardHeader className="pb-2"><CardTitle className="text-xs">{cat}</CardTitle></CardHeader><CardContent><div className="font-bold">{currency} {total.toLocaleString()}</div></CardContent></Card>
                    ) : null
                  })}
                </div>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Amount</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    {incomeList.length === 0 ? (
                      <TableRow><TableCell colSpan={4} className="text-center h-24 text-muted-foreground">No other income recorded</TableCell></TableRow>
                    ) : incomeList.map(i => (
                      <TableRow key={i.id}>
                        <TableCell>{i.incomeDate}</TableCell>
                        <TableCell>{i.category}</TableCell>
                        <TableCell>{i.description}</TableCell>
                        <TableCell>{currency} {Number(i.amount).toLocaleString()}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
                <div className="mt-4 text-right font-bold">Total: {currency} {totalOtherIncome.toLocaleString()}</div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="payroll">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Payroll Report</CardTitle>
                    <CardDescription>Teacher salary and commission payouts</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-3 mb-4">
                  <Card><CardHeader className="pb-2"><CardTitle className="text-xs">Total Payroll</CardTitle></CardHeader><CardContent><div className="font-bold text-red-600">{currency} {totalPayroll.toLocaleString()}</div></CardContent></Card>
                  <Card><CardHeader className="pb-2"><CardTitle className="text-xs">Salary Payments</CardTitle></CardHeader><CardContent><div className="font-bold">{payrollRecords.filter(r => r.payType === "SALARY" && r.status === "PAID").length}</div></CardContent></Card>
                  <Card><CardHeader className="pb-2"><CardTitle className="text-xs">Commission Payments</CardTitle></CardHeader><CardContent><div className="font-bold">{payrollRecords.filter(r => r.payType === "COMMISSION" && r.status === "PAID").length}</div></CardContent></Card>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Date</TableHead><TableHead>Teacher</TableHead><TableHead>Type</TableHead><TableHead>Period</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    {payrollRecords.length === 0 ? (
                      <TableRow><TableCell colSpan={6} className="text-center h-24 text-muted-foreground">No payroll records</TableCell></TableRow>
                    ) : payrollRecords.map(r => (
                      <TableRow key={r.id}>
                        <TableCell>{r.payDate}</TableCell>
                        <TableCell>{r.teacherName}</TableCell>
                        <TableCell>{r.payType}</TableCell>
                        <TableCell className="text-xs">{r.periodStart} to {r.periodEnd}</TableCell>
                        <TableCell>{currency} {Number(r.amount).toLocaleString()}</TableCell>
                        <TableCell>{r.status}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
                <div className="mt-4 text-right font-bold">Total: {currency} {totalPayroll.toLocaleString()}</div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="outstanding">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Outstanding Balance Report</CardTitle>
                    <CardDescription>Students with unpaid fees</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportOutstandingPDF}><FileText className="h-4 w-4 mr-1" /> PDF</Button>
                    <Button variant="outline" size="sm" onClick={handleExportOutstandingCSV}><FileSpreadsheet className="h-4 w-4 mr-1" /> CSV</Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Student</TableHead><TableHead>Course</TableHead><TableHead>Total Fee</TableHead><TableHead>Balance</TableHead><TableHead>Status</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    {fees.filter(f => f.status !== "PAID").length === 0 ? (
                      <TableRow><TableCell colSpan={5} className="text-center h-24 text-muted-foreground">No outstanding balances</TableCell></TableRow>
                    ) : (
                      fees.filter(f => f.status !== "PAID").map(f => (
                        <TableRow key={f.id}>
                          <TableCell>{f.firstName} {f.lastName}</TableCell>
                          <TableCell>{f.courseName}</TableCell>
                          <TableCell>{currency} {Number(f.totalFee).toLocaleString()}</TableCell>
                          <TableCell className="font-bold text-orange-600">{currency} {Number(f.balance).toLocaleString()}</TableCell>
                          <TableCell>{f.status}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cashflow">
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <div>
                    <CardTitle>Cash Flow Summary</CardTitle>
                    <CardDescription>Income vs Expenses</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportCashFlowPDF}><FileText className="h-4 w-4 mr-1" /> PDF</Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow><TableHead>Metric</TableHead><TableHead>Amount</TableHead></TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow><TableCell className="font-medium">Total Income</TableCell><TableCell className="text-green-600 font-bold">{currency} {totalIncome.toLocaleString()}</TableCell></TableRow>
                    <TableRow><TableCell className="font-medium">Total Expenses</TableCell><TableCell className="text-red-600 font-bold">{currency} {totalExpensesAmt.toLocaleString()}</TableCell></TableRow>
                    <TableRow><TableCell className="font-medium">Net Cash Flow</TableCell><TableCell className={`font-bold ${totalIncome - totalExpensesAmt >= 0 ? "text-green-600" : "text-red-600"}`}>{currency} {(totalIncome - totalExpensesAmt).toLocaleString()}</TableCell></TableRow>
                    <TableRow><TableCell className="font-medium">Outstanding Balances</TableCell><TableCell className="text-orange-600 font-bold">{currency} {outstandingTotal.toLocaleString()}</TableCell></TableRow>
                  </TableBody>
                </Table>

                <div className="mt-6">
                  <div className="flex justify-between items-center mb-4">
                    <h3 className="font-semibold">Profit & Loss Summary</h3>
                    <Button variant="outline" size="sm" onClick={handleExportProfitLossPDF}><FileText className="h-4 w-4 mr-1" /> PDF</Button>
                  </div>
                  <Table>
                    <TableHeader>
                      <TableRow><TableHead>Metric</TableHead><TableHead>Amount</TableHead></TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow><TableCell className="font-medium">Income (Fees Collected)</TableCell><TableCell>{currency} {totalIncome.toLocaleString()}</TableCell></TableRow>
                      <TableRow><TableCell className="font-medium">Expenses</TableCell><TableCell>{currency} {totalExpensesAmt.toLocaleString()}</TableCell></TableRow>
                      <TableRow><TableCell className="font-bold">Profit / Loss</TableCell><TableCell className={`font-bold text-lg ${totalIncome - totalExpensesAmt >= 0 ? "text-green-600" : "text-red-600"}`}>{currency} {(totalIncome - totalExpensesAmt).toLocaleString()}</TableCell></TableRow>
                    </TableBody>
                  </Table>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
  </>
  )
}
